name: CombatAndLevels
version: '${project.version}'
main: me.ethan.combatandlevels.CombatAndLevels
api-version: 1.19
authors: [ Ethan ]
description: Combat and levels
commands:
  C:
    description: "Core"